import type { Exercise, AcademicLevel, SubjectCode } from './types.ts';

export const ACADEMIC_LEVELS: AcademicLevel[] = [
  {
    code: 'LVL-1-DISCOVERY',
    levelNumber: 1,
    displayName: 'Niveau 1 — Découverte Initiale',
    gradeEquivalent: '1ère - 2ème Année Primaire',
    band: 'BAND_A',
    description: 'Calcul visuel, reconnaissance des formes, vocabulaire bilingue avec pictogrammes.',
  },
  {
    code: 'LVL-2-EXPLORER',
    levelNumber: 2,
    displayName: 'Niveau 2 — Explorateur Autonome',
    gradeEquivalent: '3ème - 4ème Année Primaire',
    band: 'BAND_A',
    description: 'Tables d’addition et de multiplication simples, phrases courtes, observation scientifique.',
  },
  {
    code: 'LVL-3-ADVENTURER',
    levelNumber: 3,
    displayName: 'Niveau 3 — Aventurier Collège',
    gradeEquivalent: '7ème - 8ème Année de Base',
    band: 'BAND_B',
    description: 'Fractions, géométrie plane, pensée algorithmique préliminaire et classification biologique.',
  },
  {
    code: 'LVL-4-VANGUARD',
    levelNumber: 4,
    displayName: 'Niveau 4 — Avant-Garde Collège',
    gradeEquivalent: '9ème Année Pilote',
    band: 'BAND_B',
    description: 'Calcul littéral, équations du 1er degré, circuits électriques et scripts Python.',
  },
  {
    code: 'LVL-5-SCHOLAR-LYCEE',
    levelNumber: 5,
    displayName: 'Niveau 5 — Lycée Tronc Commun',
    gradeEquivalent: '1ère - 2ème Année Secondaire',
    band: 'BAND_C',
    description: 'Fonctions numériques, trigonométrie, chimie des solutions et algorithmes récursifs.',
  },
  {
    code: 'LVL-6-BAC-PREP',
    levelNumber: 6,
    displayName: 'Niveau 6 — Préparation Baccalaureate',
    gradeEquivalent: 'Baccalauréat National Tunisien',
    band: 'BAND_C',
    description: 'Nombres complexes, calcul intégral, mécanique quantique/RLC et dissertation philosophique.',
  },
  {
    code: 'LVL-7-BAC-PILOTE-ELITE',
    levelNumber: 7,
    displayName: 'Niveau 7 — Baccalaureate Pilote & Concours',
    gradeEquivalent: 'Bac Pilote & Olympiades',
    band: 'BAND_C',
    description: 'Démonstrations rigoureuses, optimisation sous contraintes et concours d’accès aux classes prépas.',
  },
];

export const CURRICULUM_EXERCISES: Exercise[] = [
  // ==========================================
  // BAND A: The Explorers (Ages 6–9, Level 1–2)
  // ==========================================
  {
    id: 'ex-a-mc-01',
    subject: 'MATH',
    subjectName: 'Mathématiques Magiques',
    title: 'Les Étoiles du Sahara',
    prompt: 'Youssef le Fennec a 4 étoiles dorées. Samy lui en donne 5 de plus. Combien d’étoiles Youssef a-t-il maintenant ?',
    targetBand: 'BAND_A',
    minAcademicLevel: 1,
    levelCode: 'LVL-1-DISCOVERY',
    exerciseType: 'multiple_choice',
    points: 10,
    xpAwarded: 40,
    starsAwarded: 3,
    estimatedDurationSeconds: 60,
    explanation: '4 + 5 = 9 étoiles au total ! Compte-les une par une sur tes doigts ou sur les constellations.',
    options: [
      { id: 'opt_7', label: '7 étoiles', isCorrect: false },
      { id: 'opt_8', label: '8 étoiles', isCorrect: false },
      { id: 'opt_9', label: '9 étoiles', isCorrect: true },
      { id: 'opt_10', label: '10 étoiles', isCorrect: false },
    ],
  },
  {
    id: 'ex-a-fitb-02',
    subject: 'FRENCH',
    subjectName: 'Français Découverte',
    title: 'Les Animaux du Désert',
    prompt: 'Complète la phrase magique avec le bon mot :',
    targetBand: 'BAND_A',
    minAcademicLevel: 1,
    levelCode: 'LVL-1-DISCOVERY',
    exerciseType: 'fill_in_the_blank',
    template: 'Le fennec vit dans le {blank} et possède de grandes {blank}.',
    blanks: [
      {
        id: 'blank_desert',
        acceptedAnswers: ['désert', 'desert', 'sahara'],
        placeholder: 'lieu où il vit',
      },
      {
        id: 'blank_oreilles',
        acceptedAnswers: ['oreilles', 'oreil'],
        placeholder: 'parties de son corps',
      },
    ],
    points: 15,
    xpAwarded: 45,
    starsAwarded: 3,
    estimatedDurationSeconds: 90,
    explanation: 'Le fennec vit dans le désert (ou Sahara) et ses grandes oreilles lui permettent de dissiper la chaleur et de repérer ses proies.',
  },
  {
    id: 'ex-a-match-03',
    subject: 'SCIENCE',
    subjectName: 'Éveil Scientifique',
    title: 'Relie chaque animal à son habitat',
    prompt: 'Associe chaque compagnon de Vamos à son milieu naturel :',
    targetBand: 'BAND_A',
    minAcademicLevel: 2,
    levelCode: 'LVL-2-EXPLORER',
    exerciseType: 'matching_pairs',
    points: 20,
    xpAwarded: 50,
    starsAwarded: 4,
    estimatedDurationSeconds: 120,
    explanation: 'Chaque espèce est parfaitement adaptée à son écosystème tunisien (dunes de Douz, mer de Tabarka, oasis de Tozeur).',
    pairs: [
      { id: 'p1', left: '🦊 Fennec', right: 'Dunes du Sahara' },
      { id: 'p2', left: '🐬 Dauphin', right: 'Mer Méditerranée' },
      { id: 'p3', left: '🌴 Dattier', right: 'Oasis de Tozeur' },
      { id: 'p4', left: '🦅 Faucon', right: 'Falaises de l’Atlas' },
    ],
  },
  {
    id: 'ex-a-sa-04',
    subject: 'ARABIC',
    subjectName: 'اللغة العربية',
    title: 'كتابة اسم الحيوان الذكي',
    prompt: 'ما هو اسم حيوان الصحراء التونسي الصغير ذو الأذنين الطويلتين ؟',
    targetBand: 'BAND_A',
    minAcademicLevel: 2,
    levelCode: 'LVL-2-EXPLORER',
    exerciseType: 'short_answer',
    points: 15,
    xpAwarded: 40,
    starsAwarded: 3,
    estimatedDurationSeconds: 60,
    acceptedAnswers: ['الفنك', 'فنك', 'fennec', 'le fennec'],
    sampleAnswer: 'الفنك',
    explanation: 'الفنك هو أصغر فصيلة من الكلبيات ويعيش في الصحراء التونسية الكبرى.',
  },

  // ==========================================
  // BAND B: The Adventurers (Ages 10–13, Level 3–4)
  // ==========================================
  {
    id: 'ex-b-mc-01',
    subject: 'MATH',
    subjectName: 'Math & Logique Vanguard',
    title: 'Équilibre des Fractions Aériennes',
    prompt: 'Quelle fraction est strictement équivalente à 18 / 24 sous sa forme irréductible ?',
    targetBand: 'BAND_B',
    minAcademicLevel: 3,
    levelCode: 'LVL-3-ADVENTURER',
    exerciseType: 'multiple_choice',
    points: 20,
    xpAwarded: 75,
    starsAwarded: 3,
    estimatedDurationSeconds: 90,
    explanation: 'En divisant le numérateur et le dénominateur par leur PGCD qui est 6 : 18 ÷ 6 = 3 et 24 ÷ 6 = 4, donc 3/4.',
    options: [
      { id: 'opt_1', label: '2 / 3', isCorrect: false },
      { id: 'opt_2', label: '3 / 4', isCorrect: true },
      { id: 'opt_3', label: '9 / 12', isCorrect: false },
      { id: 'opt_4', label: '6 / 8', isCorrect: false },
    ],
  },
  {
    id: 'ex-b-fitb-02',
    subject: 'INFORMATIQUE',
    subjectName: 'Informatique & Algorithmique',
    title: 'Boucle et Condition en Python',
    prompt: 'Complète les mots-clés manquants dans ce bloc d’algorithme Vamos :',
    targetBand: 'BAND_B',
    minAcademicLevel: 4,
    levelCode: 'LVL-4-VANGUARD',
    exerciseType: 'fill_in_the_blank',
    template: 'Pour répéter 10 fois une instruction en Python, on écrit: {blank} i in range(10): puis pour tester si i est pair, on utilise {blank} i % 2 == 0.',
    blanks: [
      {
        id: 'kw_for',
        acceptedAnswers: ['for', 'pour'],
        placeholder: 'boucle',
        caseSensitive: false,
      },
      {
        id: 'kw_if',
        acceptedAnswers: ['if', 'si'],
        placeholder: 'condition',
        caseSensitive: false,
      },
    ],
    points: 25,
    xpAwarded: 85,
    starsAwarded: 4,
    estimatedDurationSeconds: 120,
    explanation: 'En Python standard, "for" initialise la boucle itérative et "if" permet l’évaluation conditionnelle d’une expression booléenne.',
  },
  {
    id: 'ex-b-match-03',
    subject: 'SCIENCE',
    subjectName: 'Sciences & Énergie',
    title: 'Formes d’Énergie et Convertisseurs',
    prompt: 'Associe chaque système technique à sa transformation énergétique principale :',
    targetBand: 'BAND_B',
    minAcademicLevel: 3,
    levelCode: 'LVL-3-ADVENTURER',
    exerciseType: 'matching_pairs',
    points: 25,
    xpAwarded: 80,
    starsAwarded: 4,
    estimatedDurationSeconds: 120,
    explanation: 'Le principe de conservation de l’énergie stipule que l’énergie ne peut être ni créée ni détruite, seulement convertie d’une forme à une autre.',
    pairs: [
      { id: 'p1', left: 'Panneau photovoltaïque', right: 'Énergie solaire ➔ Électrique' },
      { id: 'p2', left: 'Éolienne de Bizerte', right: 'Énergie cinétique ➔ Électrique' },
      { id: 'p3', left: 'Batterie au lithium', right: 'Énergie chimique ➔ Électrique' },
      { id: 'p4', left: 'Moteur de drone', right: 'Énergie électrique ➔ Mécanique' },
    ],
  },
  {
    id: 'ex-b-sa-04',
    subject: 'MATH',
    subjectName: 'Math & Algèbre',
    title: 'Résolution d’Équation Rapide',
    prompt: 'Résous l’équation : 3x - 7 = 14. Quelle est la valeur exacte de x ?',
    targetBand: 'BAND_B',
    minAcademicLevel: 4,
    levelCode: 'LVL-4-VANGUARD',
    exerciseType: 'short_answer',
    points: 20,
    xpAwarded: 70,
    starsAwarded: 3,
    estimatedDurationSeconds: 90,
    acceptedAnswers: ['7', 'x=7', 'x = 7'],
    sampleAnswer: '7',
    explanation: '3x = 14 + 7 = 21, donc x = 21 / 3 = 7.',
    numericTolerance: 0,
  },

  // ==========================================
  // BAND C: The Scholars (Ages 14–19, Level 5–7)
  // ==========================================
  {
    id: 'ex-c-mc-01',
    subject: 'MATH',
    subjectName: 'Mathématiques (Baccalauréat)',
    title: 'Forme Exponentielle des Nombres Complexes',
    prompt: 'Soit le nombre complexe z = 1 + i√3. Quelle est son écriture exponentielle exacte ?',
    targetBand: 'BAND_C',
    minAcademicLevel: 6,
    levelCode: 'LVL-6-BAC-PREP',
    exerciseType: 'multiple_choice',
    points: 25,
    xpAwarded: 100,
    starsAwarded: 3,
    estimatedDurationSeconds: 180,
    explanation: '|z| = √(1² + (√3)²) = √4 = 2. cos θ = 1/2 et sin θ = √3/2, d’où θ ≡ π/3 [2π]. Donc z = 2 · e^(iπ/3).',
    options: [
      { id: 'opt_1', label: '2 · e^(iπ/6)', isCorrect: false },
      { id: 'opt_2', label: '2 · e^(iπ/3)', isCorrect: true },
      { id: 'opt_3', label: '√2 · e^(iπ/4)', isCorrect: false },
      { id: 'opt_4', label: '4 · e^(iπ/3)', isCorrect: false },
    ],
  },
  {
    id: 'ex-c-fitb-02',
    subject: 'SCIENCE',
    subjectName: 'Physique-Chimie (Bac)',
    title: 'Circuit RLC Série & Fréquence Propre',
    prompt: 'Remplis les grandeurs fondamentales de résonance :',
    targetBand: 'BAND_C',
    minAcademicLevel: 6,
    levelCode: 'LVL-6-BAC-PREP',
    exerciseType: 'fill_in_the_blank',
    template: 'Dans un circuit RLC série excité par une tension sinusoïdale, la pulsation propre est ω₀ = {blank} et à la résonance d’intensité, l’impédance minimale Z est égale à {blank}.',
    blanks: [
      {
        id: 'omega_0',
        acceptedAnswers: ['1/sqrt(LC)', '1 / sqrt(LC)', '1/√(LC)', '1/√(lc)'],
        placeholder: 'expression de ω₀',
      },
      {
        id: 'impedance_r',
        acceptedAnswers: ['R', 'r', 'résistance', 'resistor'],
        placeholder: 'valeur de Z',
      },
    ],
    points: 30,
    xpAwarded: 110,
    starsAwarded: 4,
    estimatedDurationSeconds: 240,
    explanation: 'À la résonance d’intensité, la partie réactive s’annule : Lω₀ - 1/(Cω₀) = 0, ce qui donne ω₀ = 1/√(LC) et Z = R.',
  },
  {
    id: 'ex-c-match-03',
    subject: 'PHILOSOPHY',
    subjectName: 'Philosophie Bac',
    title: 'Concepts & Auteurs Majeurs',
    prompt: 'Associe chaque thèse philosophique à son penseur de référence au programme officiel :',
    targetBand: 'BAND_C',
    minAcademicLevel: 6,
    levelCode: 'LVL-6-BAC-PREP',
    exerciseType: 'matching_pairs',
    points: 30,
    xpAwarded: 120,
    starsAwarded: 4,
    estimatedDurationSeconds: 240,
    explanation: 'Maîtrise des doctrines de la liberté, du contrat social, de la dialectique et de la justice institutionnelle.',
    pairs: [
      { id: 'p1', left: 'L’impératif catégorique et autonomie morale', right: 'Emmanuel Kant' },
      { id: 'p2', left: 'Le Contrat Social et la volonté générale', right: 'Jean-Jacques Rousseau' },
      { id: 'p3', left: 'Théorie de la justice comme équité', right: 'John Rawls' },
      { id: 'p4', left: 'La dialectique du maître et de l’esclave', right: 'G.W.F. Hegel' },
    ],
  },
  {
    id: 'ex-c-sa-04',
    subject: 'MATH',
    subjectName: 'Calcul Différentiel & Intégral',
    title: 'Limite Remarquable en Zéro',
    prompt: 'Calcule la limite quand x tend vers 0 de f(x) = (sin(3x)) / x.',
    targetBand: 'BAND_C',
    minAcademicLevel: 6,
    levelCode: 'LVL-6-BAC-PREP',
    exerciseType: 'short_answer',
    points: 25,
    xpAwarded: 100,
    starsAwarded: 3,
    estimatedDurationSeconds: 150,
    acceptedAnswers: ['3', '3.0', 'lim = 3', 'limite 3'],
    sampleAnswer: '3',
    explanation: 'On écrit (sin(3x))/x = 3 · (sin(3x))/(3x). Comme lim_{u→0} (sin u)/u = 1, la limite vaut 3 · 1 = 3.',
    numericTolerance: 0,
  },

  // --- Band A Additional Curricular Pairs & Math Facts ---
  {
    id: 'ex-a-match-vocab',
    subject: 'FRENCH',
    subjectName: 'Vocabulaire Bilingue',
    title: 'Mots & Pictogrammes de la Nature',
    prompt: 'Associe chaque mot en français à son équivalent arabe avec son pictogramme :',
    targetBand: 'BAND_A',
    minAcademicLevel: 1,
    levelCode: 'LVL-1-DISCOVERY',
    exerciseType: 'matching_pairs',
    points: 15,
    xpAwarded: 45,
    starsAwarded: 3,
    estimatedDurationSeconds: 90,
    explanation: 'Apprentissage du vocabulaire bilingue avec pictogrammes visuels adaptés aux 6–9 ans.',
    pairs: [
      { id: 'v1', left: '🐱 Chaton', right: 'قطة صغيرة' },
      { id: 'v2', left: '🌙 Étoile & Lune', right: 'قمر و نجوم' },
      { id: 'v3', left: '🌴 Palmier', right: 'نخلة واحة' },
      { id: 'v4', left: '🐪 Chameau', right: 'جمل صحراوي' },
    ],
  },
  {
    id: 'ex-a-mc-math-facts',
    subject: 'MATH',
    subjectName: 'Calcul Magique',
    title: 'Les Doubles Magiques',
    prompt: 'Youssef le Fennec regarde deux groupes de 3 étoiles. Combien font 3 + 3 ?',
    targetBand: 'BAND_A',
    minAcademicLevel: 1,
    levelCode: 'LVL-1-DISCOVERY',
    exerciseType: 'multiple_choice',
    points: 10,
    xpAwarded: 35,
    starsAwarded: 3,
    estimatedDurationSeconds: 45,
    explanation: 'Le double de 3 est 6 (3 + 3 = 6).',
    options: [
      { id: 'opt_5', label: '5 étoiles', isCorrect: false },
      { id: 'opt_6', label: '6 étoiles', isCorrect: true },
      { id: 'opt_7', label: '7 étoiles', isCorrect: false },
    ],
  },
  {
    id: 'ex-a-mc-speed',
    subject: 'MATH',
    subjectName: 'Calcul Rapide',
    title: 'Le Défi des Étoiles',
    prompt: 'Quel est le double de 5 ?',
    targetBand: 'BAND_A',
    minAcademicLevel: 1,
    levelCode: 'LVL-1-DISCOVERY',
    exerciseType: 'multiple_choice',
    points: 10,
    xpAwarded: 35,
    starsAwarded: 3,
    estimatedDurationSeconds: 45,
    explanation: '5 + 5 = 10.',
    options: [
      { id: 'opt_8', label: '8', isCorrect: false },
      { id: 'opt_10', label: '10', isCorrect: true },
      { id: 'opt_12', label: '12', isCorrect: false },
    ],
  },

  // --- Band B Additional Curricular Pairs & Math Facts ---
  {
    id: 'ex-b-match-vocab',
    subject: 'INFORMATIQUE',
    subjectName: 'Concepts Numériques',
    title: 'Vocabulaire Numérique & Algorithmes',
    prompt: 'Associe chaque terme informatique à sa définition précise :',
    targetBand: 'BAND_B',
    minAcademicLevel: 3,
    levelCode: 'LVL-3-ADVENTURER',
    exerciseType: 'matching_pairs',
    points: 20,
    xpAwarded: 70,
    starsAwarded: 4,
    estimatedDurationSeconds: 90,
    explanation: 'Concepts fondamentaux du codage et de l’informatique au collège.',
    pairs: [
      { id: 'p1', left: 'Variable', right: 'Boîte en mémoire stockant une valeur' },
      { id: 'p2', left: 'Algorithme', right: 'Suite ordonnée d’instructions' },
      { id: 'p3', left: 'Boucle', right: 'Répétition contrôlée d’un bloc de code' },
      { id: 'p4', left: 'Condition', right: 'Test logique déterminant une action' },
    ],
  },
  {
    id: 'ex-b-mc-math-facts',
    subject: 'MATH',
    subjectName: 'Calcul Mental Rapide',
    title: 'Tables de Multiplication Éclair',
    prompt: 'Quel est le résultat immédiat de 7 × 8 ?',
    targetBand: 'BAND_B',
    minAcademicLevel: 3,
    levelCode: 'LVL-3-ADVENTURER',
    exerciseType: 'multiple_choice',
    points: 15,
    xpAwarded: 60,
    starsAwarded: 3,
    estimatedDurationSeconds: 30,
    explanation: '7 × 8 = 56.',
    options: [
      { id: 'opt_54', label: '54', isCorrect: false },
      { id: 'opt_56', label: '56', isCorrect: true },
      { id: 'opt_64', label: '64', isCorrect: false },
      { id: 'opt_48', label: '48', isCorrect: false },
    ],
  },
  {
    id: 'ex-b-mc-physics',
    subject: 'SCIENCE',
    subjectName: 'Physique Collège',
    title: 'Unités du Système International',
    prompt: 'Quelle est l’unité légale de la résistance électrique dans le circuit ?',
    targetBand: 'BAND_B',
    minAcademicLevel: 4,
    levelCode: 'LVL-4-VANGUARD',
    exerciseType: 'multiple_choice',
    points: 15,
    xpAwarded: 65,
    starsAwarded: 3,
    estimatedDurationSeconds: 45,
    explanation: 'La résistance électrique se mesure en Ohms (symbole Ω).',
    options: [
      { id: 'opt_v', label: 'Volt (V)', isCorrect: false },
      { id: 'opt_a', label: 'Ampère (A)', isCorrect: false },
      { id: 'opt_w', label: 'Watt (W)', isCorrect: false },
      { id: 'opt_ohm', label: 'Ohm (Ω)', isCorrect: true },
    ],
  },
  {
    id: 'ex-b-mc-geometry',
    subject: 'MATH',
    subjectName: 'Géométrie Collège',
    title: 'Théorème de Pythagore',
    prompt: 'Dans un triangle rectangle dont les côtés de l’angle droit mesurent 3 cm et 4 cm, quelle est la longueur de l’hypoténuse ?',
    targetBand: 'BAND_B',
    minAcademicLevel: 3,
    levelCode: 'LVL-3-ADVENTURER',
    exerciseType: 'multiple_choice',
    points: 20,
    xpAwarded: 75,
    starsAwarded: 3,
    estimatedDurationSeconds: 45,
    explanation: 'D’après le théorème de Pythagore : 3² + 4² = 9 + 16 = 25 = 5². L’hypoténuse mesure 5 cm.',
    options: [
      { id: 'opt_5', label: '5 cm', isCorrect: true },
      { id: 'opt_6', label: '6 cm', isCorrect: false },
      { id: 'opt_7', label: '7 cm', isCorrect: false },
      { id: 'opt_root7', label: '√7 cm', isCorrect: false },
    ],
  },
  {
    id: 'ex-b-mc-astronomy',
    subject: 'SCIENCE',
    subjectName: 'Système Solaire',
    title: 'Planètes du Système Solaire',
    prompt: 'Quelle est la planète la plus proche du Soleil dans notre système solaire ?',
    targetBand: 'BAND_B',
    minAcademicLevel: 3,
    levelCode: 'LVL-3-ADVENTURER',
    exerciseType: 'multiple_choice',
    points: 15,
    xpAwarded: 60,
    starsAwarded: 3,
    estimatedDurationSeconds: 30,
    explanation: 'Mercure est la planète la plus proche du Soleil, suivie de Vénus, de la Terre et de Mars.',
    options: [
      { id: 'opt_venus', label: 'Vénus', isCorrect: false },
      { id: 'opt_mercure', label: 'Mercure', isCorrect: true },
      { id: 'opt_mars', label: 'Mars', isCorrect: false },
      { id: 'opt_jupiter', label: 'Jupiter', isCorrect: false },
    ],
  },

  // --- Band C Additional Curricular Pairs & Bac Blitz Questions ---
  {
    id: 'ex-c-match-math',
    subject: 'MATH',
    subjectName: 'Formules & Identités Remarquables',
    title: 'Dérivées et Primitives Essentielles',
    prompt: 'Associe chaque fonction à sa dérivée sur son intervalle de définition :',
    targetBand: 'BAND_C',
    minAcademicLevel: 6,
    levelCode: 'LVL-6-BAC-PREP',
    exerciseType: 'matching_pairs',
    points: 25,
    xpAwarded: 95,
    starsAwarded: 4,
    estimatedDurationSeconds: 120,
    explanation: 'Formulaire officiel du Baccalauréat tunisien en Analyse mathématique.',
    pairs: [
      { id: 'm1', left: 'f(x) = ln(x) (x > 0)', right: 'f’(x) = 1/x' },
      { id: 'm2', left: 'f(x) = e^(2x)', right: 'f’(x) = 2 · e^(2x)' },
      { id: 'm3', left: 'f(x) = sin(3x)', right: 'f’(x) = 3 · cos(3x)' },
      { id: 'm4', left: 'f(x) = 1/x', right: 'f’(x) = -1/x²' },
    ],
  },
  {
    id: 'ex-c-mc-bac-blitz-01',
    subject: 'MATH',
    subjectName: 'Mathématiques Rapides',
    title: 'Dérivée Exponentielle Rapide',
    prompt: 'Quelle est la fonction dérivée de g(x) = e^(3x + 1) ?',
    targetBand: 'BAND_C',
    minAcademicLevel: 6,
    levelCode: 'LVL-6-BAC-PREP',
    exerciseType: 'multiple_choice',
    points: 20,
    xpAwarded: 85,
    starsAwarded: 3,
    estimatedDurationSeconds: 20,
    explanation: 'D’après la formule (e^u)’ = u’ · e^u, pour u(x) = 3x + 1 on a u’(x) = 3, donc g’(x) = 3e^(3x+1).',
    options: [
      { id: 'opt_1', label: 'e^(3x + 1)', isCorrect: false },
      { id: 'opt_2', label: '3 · e^(3x + 1)', isCorrect: true },
      { id: 'opt_3', label: '(3x + 1) · e^(3x)', isCorrect: false },
      { id: 'opt_4', label: '3 · e^(3x)', isCorrect: false },
    ],
  },
  {
    id: 'ex-c-mc-bac-blitz-02',
    subject: 'PHILOSOPHY',
    subjectName: 'Philosophie & Épistémologie',
    title: 'Concepts Fondamentaux',
    prompt: 'À quel auteur associe-t-on la formule philosophique fondamentale « Je pense, donc je suis » ?',
    targetBand: 'BAND_C',
    minAcademicLevel: 5,
    levelCode: 'LVL-5-SCHOLAR-LYCEE',
    exerciseType: 'multiple_choice',
    points: 15,
    xpAwarded: 70,
    starsAwarded: 3,
    estimatedDurationSeconds: 20,
    explanation: 'René Descartes dans le Discours de la Méthode (1637) établit le cogito comme première certitude.',
    options: [
      { id: 'opt_spinoza', label: 'Baruch Spinoza', isCorrect: false },
      { id: 'opt_descartes', label: 'René Descartes', isCorrect: true },
      { id: 'opt_kant', label: 'Emmanuel Kant', isCorrect: false },
      { id: 'opt_platon', label: 'Platon', isCorrect: false },
    ],
  },
  {
    id: 'ex-c-mc-bac-blitz-03',
    subject: 'SCIENCE',
    subjectName: 'Physique Ondulatoire',
    title: 'Vitesse de la Lumière dans le Vide',
    prompt: 'Quelle est la valeur approchée admise de la célérité c de la lumière dans le vide ?',
    targetBand: 'BAND_C',
    minAcademicLevel: 5,
    levelCode: 'LVL-5-SCHOLAR-LYCEE',
    exerciseType: 'multiple_choice',
    points: 15,
    xpAwarded: 70,
    starsAwarded: 3,
    estimatedDurationSeconds: 20,
    explanation: 'c ≈ 3 × 10^8 m/s (exactement 299 792 458 m/s).',
    options: [
      { id: 'opt_3e6', label: '3 × 10^6 m/s', isCorrect: false },
      { id: 'opt_3e8', label: '3 × 10^8 m/s', isCorrect: true },
      { id: 'opt_3e10', label: '3 × 10^10 m/s', isCorrect: false },
    ],
  },
  {
    id: 'ex-c-mc-bac-blitz-04',
    subject: 'MATH',
    subjectName: 'Nombres Complexes Bac',
    title: 'Module d’un Nombre Complexe',
    prompt: 'Quel est le module du nombre complexe z = 3 + 4i ?',
    targetBand: 'BAND_C',
    minAcademicLevel: 6,
    levelCode: 'LVL-6-BAC-PREP',
    exerciseType: 'multiple_choice',
    points: 20,
    xpAwarded: 85,
    starsAwarded: 3,
    estimatedDurationSeconds: 20,
    explanation: '|z| = √(3² + 4²) = √(9 + 16) = √25 = 5.',
    options: [
      { id: 'opt_mod_5', label: '5', isCorrect: true },
      { id: 'opt_mod_7', label: '7', isCorrect: false },
      { id: 'opt_mod_25', label: '25', isCorrect: false },
      { id: 'opt_mod_12', label: '12', isCorrect: false },
    ],
  },
  {
    id: 'ex-c-mc-bac-blitz-05',
    subject: 'SCIENCE',
    subjectName: 'Chimie des Solutions',
    title: 'Constante d’Avogadro',
    prompt: 'Quelle est la valeur numérique approchée de la constante d’Avogadro NA ?',
    targetBand: 'BAND_C',
    minAcademicLevel: 6,
    levelCode: 'LVL-6-BAC-PREP',
    exerciseType: 'multiple_choice',
    points: 20,
    xpAwarded: 80,
    starsAwarded: 3,
    estimatedDurationSeconds: 20,
    explanation: 'NA ≈ 6,022 × 10^23 mol⁻¹.',
    options: [
      { id: 'opt_avo_23', label: '6,02 × 10²³ mol⁻¹', isCorrect: true },
      { id: 'opt_avo_19', label: '1,60 × 10⁻¹⁹ C', isCorrect: false },
      { id: 'opt_avo_34', label: '6,62 × 10⁻³⁴ J·s', isCorrect: false },
      { id: 'opt_avo_8', label: '8,314 J·K⁻¹·mol⁻¹', isCorrect: false },
    ],
  },
];
